name: Build

on:
  # Pull requests targeting main
  pull_request:
    branches: [ main ]
    
    # opened: when a PR is created
    # reopened: when a PR is reopened
    # synchronize: when commits are pushed to an open PR
    types: [opened, reopened, synchronize]

  # Manually triggered
  workflow_dispatch:    

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Install Format Tool
        run: dotnet tool install -g dotnet-format

      - name: Check Format
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Build
        run: dotnet build --no-restore -c Release --warnAsError

      - name: Tests
        run: dotnet test --no-build --no-restore -c Release tests/Xes.UnitTests/Xes.Tests.csproj
